version: '3.7'

services:
  web:
    container_name: shoppinglist-web
    build:
      context: .
    command: sh -c 'npm run start'
    ports:
      - "1234:1234"
    volumes:
      - ./src:/data/src/src
